name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'


    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Inject license_key in newrelic.yml
      run: sed -i 's/<REPLACE_WITH_NEWRELIC_LICENSE_KEY>/${{ secrets.NEW_RELIC_LICENSE_KEY }}/' newrelic/newrelic*.yml
    - name: Build and tag Docker image
      run: |
        docker build -t iamvijayp/hiworld-v2:${{ github.sha }} .
        docker tag iamvijayp/hiworld-v2:${{ github.sha }} iamvijayp/hiworld-v2:latest
    - name: Log into Docker Hub
      run: docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: docker push iamvijayp/hiworld-v2
  
  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Log into Docker Hub
      run: docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ env.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'iamvijayp/hiworld-v2:${{ github.sha }}'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "test stage"
          cat /etc/os-release
          grep pro /proc/cpuinfo
          uptime && who
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: deploy
          run: echo "deploy stage"

