name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # env:
    #   DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    #   DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Generate JaCoCo report
        run: mvn jacoco:report
      - name: Code Coverage
        run: awk -F, ' { instructions += $4 + $5; covered += $5 } END { coverage=100*covered/instructions; print coverage, "% covered"; if (coverage < 40) { print "Aborting! Code coverage is less than 50%."; exit 1 } }' target/site/jacoco/jacoco.csv

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-html-report
          path: target/site/jacoco/
          
      - name: Inject license_key in newrelic.yml
        run: sed -i 's/<REPLACE_WITH_NEWRELIC_LICENSE_KEY>/${{ secrets.NEW_RELIC_LICENSE_KEY }}/' newrelic/newrelic*.yml
      - name: Build and tag Docker image
        run: |
          docker build -t iamvijayp/hiworld-v2:${{ github.sha }} .
          docker tag iamvijayp/hiworld-v2:${{ github.sha }} iamvijayp/hiworld-v2:latest
      - name: Log into Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push iamvijayp/hiworld-v2

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'iamvijayp/hiworld-v2:latest'
          format: 'table'
          # exit-code: '1' #Exit code when specified vulnerabilities are found
          ignore-unfixed: false
          vuln-type: 'os,library'
